/** Danh sách tiện nghi phòng — dùng chung admin / owner */
export const ROOM_FACILITY_OPTIONS = [
  'TV',
  'Wifi',
  'Minibar',
  'Điều hòa',
  'Bồn tắm',
  'Ban công',
  'Két sắt',
  'Bàn làm việc',
  'Tủ lạnh',
  'Máy pha cà phê',
  'Điện thoại',
  'Máy sấy tóc',
  'Bàn trang điểm',
  'Ghế sofa',
  'Giường đôi',
  'Giường đơn',
  'Tủ quần áo',
  'Khu vực tiếp khách',
  'Phòng tắm riêng',
  'Vòi sen',
  'Bồn tắm jacuzzi',
  'Bếp mini',
  'Lò vi sóng',
  'Máy rửa bát',
  'Bàn ăn',
  'Khu vực làm việc',
  'Máy chiếu',
  'Hệ thống âm thanh',
  'Điều khiển thông minh',
  'Rèm cửa tự động',
  'An ninh 24/7',
  'Dịch vụ phòng',
  'Dọn dẹp hàng ngày',
  'Dịch vụ giặt ủi',
  'Phòng gym',
  'Hồ bơi',
  'Spa',
  'Massage',
  'Xông hơi',
  'Phòng xông hơi khô',
];
